name: Build & Deploy Portfolio + Blog

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_SUBMODULE_BLOG_TOKEN }}
          submodules: recursive
          fetch-depth: 0

      # ---- Copy static portfolio (root) ----
      - name: Copy portfolio files
        run: |
          mkdir -p public
          rsync -av --exclude 'public' --exclude '.git' --exclude '.github' ./ ./public/

      # ---- Build blog (Hugo submodule) ----
      - name: Install Hugo (extended)
        run: |
          HUGO_VER=0.134.2
          wget -qO- "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VER}/hugo_extended_${HUGO_VER}_Linux-64bit.tar.gz" \
          | tar -xz hugo
          sudo mv hugo /usr/local/bin/hugo

      - name: Build blog into public/blog
        working-directory: ./blogs
        run: |
          hugo --minify --baseURL "/blog/" --destination ../public/blog

      # ---- Setup domain / nojekyll ----
      - name: Setup CNAME + .nojekyll
        run: |
          echo "kaustuvprajapati.com.np" > public/CNAME
          touch public/.nojekyll

      # ---- Upload artifact for Pages ----
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
