name: Build docs (Portfolio + Blog)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Hugo (extended)
        run: |
          HUGO_VER=0.134.2
          wget -qO- https://github.com/gohugoio/hugo/releases/download/v${HUGO_VER}/hugo_extended_${HUGO_VER}_Linux-64bit.tar.gz \
          | tar -xz hugo
          sudo mv hugo /usr/local/bin/hugo

      - name: Build blog into docs/blog
        working-directory: ./blog
        run: |
          BASE_URL="https://$GITHUB_REPOSITORY_OWNER.github.io/${GITHUB_REPOSITORY#*/}/blog/"
          [ -n "${CUSTOM_DOMAIN}" ] && BASE_URL="https://${CUSTOM_DOMAIN}/blog/"
          mkdir -p ../docs/blog
          hugo --minify --baseURL "$BASE_URL" --destination ../docs/blog
